"""pitch category add

Revision ID: da2579fd0825
Revises: 62dd8dd221b4
Create Date: 2018-09-08 12:32:49.572005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da2579fd0825'
down_revision = '62dd8dd221b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('category', sa.String(length=255), nullable=True))
    op.drop_column('pitches', 'pitch_category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pitch_category', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('pitches', 'category')
    # ### end Alembic commands ###
